### ISSUE TITLE
Error instalando el modulo

### ISSUE THREAD

**Issue by FacundoMainere** [gcoop-libre/cooperative_ar#2]
Hola, cuando marco para instalar el modulo en el cliente de tryton recibo el siguiente error:

`The value "1" of field "Company" on "Analytic Account" doesn't exist.`

También probé updateando desde la db con:

`trytond -d tryton_db -u all`

y tira un error similar.
![screenshot from 2014-12-19 16 33 34](https://cloud.githubusercontent.com/assets/1382608/5510078/6779c9b8-879d-11e4-8a5b-cb857ecc6aad.png)
![screenshot from 2014-12-19 16 33 47](https://cloud.githubusercontent.com/assets/1382608/5510079/677a0216-879d-11e4-98bc-361329c21f98.png)
![screenshot from 2014-12-19 16 33 54](https://cloud.githubusercontent.com/assets/1382608/5510080/677a59fa-879d-11e4-815b-823f25589e2c.png)

**Comment by ceciliasp** [comment]
Yo tengo el mismo problema. Versión 3.2
