### ISSUE TITLE
Dependencia de Invoice_Ar

### ISSUE THREAD

**Issue by agumontagna** [gcoop-libre/cooperative_ar#4]
Probando el módulo, al intentar imprimir recibos pide un campo que solamente se puede completar para la compañia, instalando el módulo INVOICE_AR. 
Me parece que habría que poner la dependencia de cooperative de invoice_ar.

**Comment by lukio** [comment]
Que se tenga que instalar todo el sistema de factura electrónica para que podamos imprimir el reporte de recibo de cooperativa me parece demasiado.

Capaz, convendria crear un nuevo módulo llamado party_ar con toda la información que se necesite de AFIP, etc y dejar el módulo de account_invoice_ar únicamente con lo relacionado a invoice.

**Comment by agumontagna** [comment]
Sí, es lo más criterioso hacer la subdivisión.
